//
//  RecentInteractor.swift
//  youtube-loader-ios
//
//  Created by Dima Virych on 26.01.2020.
//  Copyright (c) 2020 Virych. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

final class RecentInteractor {
    
    let provider: ListDataProvider
    
    init(provider: ListDataProvider) {
        self.provider = provider
    }
}

// MARK: - Extensions -

extension RecentInteractor: RecentInteractorInterface {
    
    var videos: [UIVideoElement] {
        provider.listOfVideos()
    }
}
