//
//  RecentPresenter.swift
//  youtube-loader-ios
//
//  Created by Dima Virych on 26.01.2020.
//  Copyright (c) 2020 Virych. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class RecentPresenter {

    // MARK: - Private properties -

    private unowned let view: RecentViewInterface
    private let interactor: RecentInteractorInterface
    private let wireframe: RecentWireframeInterface

    // MARK: - Lifecycle -

    init(view: RecentViewInterface, interactor: RecentInteractorInterface, wireframe: RecentWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension RecentPresenter: RecentPresenterInterface {
    
    func videoSelected(at index: Int) {
        
        wireframe.showDetailScreen(for: video(for: index))
    }
    
    
    func video(for item: Int) -> UIVideoElement {
        
        interactor.videos[item]
    }
    
    func numberOfItemsInSection(_ section: Int) -> Int {
        
        interactor.videos.count
    }
    
}
