//
//  RecentInterfaces.swift
//  youtube-loader-ios
//
//  Created by Dima Virych on 26.01.2020.
//  Copyright (c) 2020 Virych. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import BaseViper
import Core

protocol RecentWireframeInterface {
}

protocol RecentViewInterface: ViewInterface {
}

protocol RecentPresenterInterface: PresenterInterface {
    
    func numberOfItemsInSection(_ section: Int) -> Int
    func video(for item: Int) -> Video
}

protocol RecentInteractorInterface: InteractorInterface {
    
    var videos: [Video] { get }
}
