//
//  RecentInterfaces.swift
//  youtube-loader-ios
//
//  Created by Dima Virych on 26.01.2020.
//  Copyright (c) 2020 Virych. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import BaseViper

protocol RecentWireframeInterface: BaseWireframe {
    
    func showDetailScreen(for video: UIVideoElement)
}

protocol RecentViewInterface: ViewInterface {
}

protocol RecentPresenterInterface: PresenterInterface {
    
    func numberOfItemsInSection(_ section: Int) -> Int
    func video(for item: Int) -> UIVideoElement
    
    func videoSelected(at index: Int)
}

protocol RecentInteractorInterface: InteractorInterface {
    
    var videos: [UIVideoElement] { get }
}
