//
//  DashboardInterfaces.swift
//  youtube-loader-ios
//
//  Created by Dima Virych on 26.01.2020.
//  Copyright (c) 2020 Virych. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import BaseViper

protocol DashboardWireframeInterface {

}

protocol DashboardViewInterface: ViewInterface {

    func fill(_ viewModel: VideoViewModel)
    func fill(_ error: Error)
}

protocol DashboardPresenterInterface: PresenterInterface {

    func url(from text: String?) -> URL?
    func fetch(for url: URL)
}

protocol DashboardInteractorInterface: InteractorInterface {
    
    var service: FetchService { get }
    var output: ((ProcessingResult) -> Void)! { get set }
    
    func fetchData(_ url: URL)
}
