//
//  DashboardInterfaces.swift
//  youtube-loader-ios
//
//  Created by Dima Virych on 26.01.2020.
//  Copyright (c) 2020 Virych. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import BaseViper

protocol DashboardWireframeInterface: BaseWireframe {

    func fillLoaded(video: UIVideoElement)
}

protocol DashboardViewInterface: ViewInterface {

    func fill()
    func fill(_ error: Error)
}

protocol DashboardPresenterInterface: PresenterInterface {

    func url(from text: String?) -> URL?
    func fetch(for url: URL)
}

protocol DashboardInteractorInterface: InteractorInterface {
    
    var output: ((Result<UIVideoElement, Error>) -> Void)! { get set }
    
    func fetchData(_ url: URL)
}
