//
//  DashboardWireframe.swift
//  youtube-loader-ios
//
//  Created by Dima Virych on 26.01.2020.
//  Copyright (c) 2020 Virych. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import BaseViper

final class DashboardWireframe: BaseWireframe {
    
    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Dashboard", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: DashboardViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = DashboardInteractor()
        let presenter = DashboardPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension DashboardWireframe: DashboardWireframeInterface {
}
