//
//  DashboardInteractor.swift
//  youtube-loader-ios
//
//  Created by Dima Virych on 26.01.2020.
//  Copyright (c) 2020 Virych. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class DashboardInteractor {

    var output: ((Result<UIVideoElement, Error>) -> Void)!
    let service: DashboardFetch
    
    init(_ service: DashboardFetch) {
        
        self.service = service
    }
}

// MARK: - Extensions -

extension DashboardInteractor: DashboardInteractorInterface {
    
    func fetchData(_ url: URL) {
        
        service.fetch(for: url, completion: output)
    }
}
