//
//  DashboardViewController.swift
//  youtube-loader-ios
//
//  Created by Dima Virych on 26.01.2020.
//  Copyright (c) 2020 Virych. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DashboardViewController: UIViewController {
    
    @IBOutlet private weak var errorLabel: UILabel!
    @IBOutlet private weak var textField: UITextField!
    
    var hud: HUD?
    

    // MARK: - Public properties -

    var presenter: DashboardPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    
    @IBAction private func fetch(_ sender: UIButton) {
        
        if let url = presenter.url(from: textField.text) {
            hud = HUD.show(on: view)
            presenter.fetch(for: url)
        }
    }
}

// MARK: - Extensions -

extension DashboardViewController: DashboardViewInterface {
   
    func fill(_ viewModel: VideoViewModel) {

        hud?.hide()
        errorLabel.isHidden = true
        navigationController?.pushWireframe(DetailWireframe(viewModel: viewModel))
    }
    
    func fill(_ error: Error) {
        
        hud?.hide()
        errorLabel.isHidden = false
        errorLabel.text = "\(error)"
    }
}
