//
//  DashboardInteractor.swift
//  youtube-loader-ios
//
//  Created by Dima Virych on 26.01.2020.
//  Copyright (c) 2020 Virych. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Core

final class DashboardInteractor {

    var output: FetchResultBlock!
    let engine: Engine
    
    init() {
        
        self.engine = Engine()
    }
}

// MARK: - Extensions -

extension DashboardInteractor: DashboardInteractorInterface {
    
    func fetchData(_ url: URL) {
        
        engine.fetchInfo(for: url, completion: output)
    }
}
