//
//  DetailInteractor.swift
//  youtube-loader-ios
//
//  Created by Dima Virych on 26.01.2020.
//  Copyright (c) 2020 Virych. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Core

final class DetailInteractor {
    
    let engine = Engine()
    var output: ((Resource?, Error?) -> Void)!
}

// MARK: - Extensions -

extension DetailInteractor: DetailInteractorInterface {
    
    func download(_ item: Resource) {
        
        engine.download(item: item, completion: output)
    }
    
    func set(dest: String, for resource: Resource) {
        
        engine.set(destenation: dest, for: resource)
    }
}
