//
//  DetailInterfaces.swift
//  youtube-loader-ios
//
//  Created by Dima Virych on 26.01.2020.
//  Copyright (c) 2020 Virych. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import BaseViper

protocol DetailWireframeInterface: BaseWireframe {
}

protocol DetailViewInterface: ViewInterface {
    
    func fill(_: Float)
    func finish()
}

protocol DetailPresenterInterface: PresenterInterface {
    
    var imageURL: URL? { get }
    var numberOfRows: Int { get }
    
    func title(for row: Int) -> String
    func download(at row: Int)
    
    func process(local url: URL)
}

protocol DetailInteractorInterface: InteractorInterface {
    
    var output: ((UIVideoElement.Resource?, Error?) -> Void)! { get set }
    var progress: ((Int) -> Void)? { get set }
    func download(_ item: UIVideoElement.Resource)
    func set(dest: String, for resource: UIVideoElement.Resource)
}
