//
//  DetailPresenter.swift
//  youtube-loader-ios
//
//  Created by Dima Virych on 26.01.2020.
//  Copyright (c) 2020 Virych. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import AVFoundation
import Core

final class DetailPresenter {

    // MARK: - Private properties -

    private unowned let view: DetailViewInterface
    private let interactor: DetailInteractorInterface
    private let wireframe: DetailWireframeInterface
    
    var video: Video!
    
    var currentExt: String!
    

    // MARK: - Lifecycle -

    init(view: DetailViewInterface, interactor: DetailInteractorInterface, wireframe: DetailWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
        
        interactor.output = { [weak self] (item, error) in
            self?.process(local: item?.destinationUrl)
        }
    }
}

// MARK: - Extensions -

extension DetailPresenter: DetailPresenterInterface {
    
    var imageURL: URL? {
        
        URL(string: video.thumbnail)
    }
    
    var numberOfRows: Int {
    
        video.resources.count
    }
    
    func title(for row: Int) -> String {
        
        video.resources[row].format + " " + video.resources[row].filesize
    }
    
    func download(at row: Int) {
        
        currentExt = video.resources[row].resourceExtension
        
        if let destenation = destinationURL(file: video.resources[row].url) {
            
            interactor.set(dest: destenation.path, for: video.resources[row])
            interactor.download(video.resources[row])
        }
    }
    
    func destinationURL(file url: URL) -> URL? {
        
        guard let documentsDirectoryURL = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
            return nil
        }
        
        let destinationURL = documentsDirectoryURL.appendingPathComponent(UUID().uuidString).appendingPathExtension(currentExt)
        
        return destinationURL
    }
    
    func process(local url: URL?) {
        
        guard let url = url else {
            return
        }
        
        DispatchQueue.main.async { [weak self] in
            let activityViewController = UIActivityViewController(activityItems: [url, "Check this out!"], applicationActivities: nil)
            self?.wireframe.viewController.present(activityViewController, animated: true)
        }
    }
}
