//
//  DetailInteractor.swift
//  youtube-loader-ios
//
//  Created by Dima Virych on 26.01.2020.
//  Copyright (c) 2020 Virych. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class DetailInteractor {
    
    let service: DetailInput
    var output: ((UIVideoElement.Resource?, Error?) -> Void)!
    
    init(input: DetailInput) {
        self.service = input
    }
}

// MARK: - Extensions -

extension DetailInteractor: DetailInteractorInterface {
    
    func download(_ item: UIVideoElement.Resource) {
        
        service.download(item, completion: output)
    }
    
    func set(dest: String, for resource: UIVideoElement.Resource) {
        
        service.set(dest: dest, for: resource)
    }
}
