//
//  DetailInterfaces.swift
//  youtube-loader-ios
//
//  Created by Dima Virych on 26.01.2020.
//  Copyright (c) 2020 Virych. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import BaseViper
import Core

protocol DetailWireframeInterface: BaseWireframe {
}

protocol DetailViewInterface: ViewInterface {
    
}

protocol DetailPresenterInterface: PresenterInterface {
    
    var imageURL: URL? { get }
    var numberOfRows: Int { get }
    
    func title(for row: Int) -> String
    func download(at row: Int)
    
    func process(local url: URL?)
}

protocol DetailInteractorInterface: InteractorInterface {
    
    var output: ((Resource?, Error?) -> Void)! { get set }
    func download(_ item: Resource)
    func set(dest: String, for resource: Resource)
}
