//
//  DetailPresenter.swift
//  youtube-loader-ios
//
//  Created by Dima Virych on 26.01.2020.
//  Copyright (c) 2020 Virych. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import AVFoundation
import Networking

public class DownloadItem: Downloadable {
    
    public let id: String
    public let fileSize: Int
    public let url: URL
    public let destinationUrl: URL
    public let downloaded: Bool
    
    public var didStartDownloading: ((Downloadable) -> Void)?
    public var didUpdateProgress: ((Downloadable, Int) -> Void)?
    public var didFinishDownloading: ((Downloadable, Error?) -> Void)?
    
    init(_ url: URL, dest: URL) {
        
        self.id = UUID().uuidString
        self.fileSize = -1
        self.url = url
        self.destinationUrl = dest
        self.downloaded = false
    }
}

final class DetailPresenter {

    // MARK: - Private properties -

    private unowned let view: DetailViewInterface
    private let interactor: DetailInteractorInterface
    private let wireframe: DetailWireframeInterface
    
    var viewModel: VideoViewModel!
    
    var currentExt: String!
    

    // MARK: - Lifecycle -

    init(view: DetailViewInterface, interactor: DetailInteractorInterface, wireframe: DetailWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
        
        interactor.output = { [weak self] (item, error) in
            self?.process(local: item.destinationUrl)
        }
    }
}

// MARK: - Extensions -

extension DetailPresenter: DetailPresenterInterface {
    
    var imageURL: URL? {
        
        URL(string: viewModel.thumbnail)
    }
    
    var numberOfRows: Int {
    
        viewModel.streams.count
    }
    
    func title(for row: Int) -> String {
        
        viewModel.streams[row].resolution
    }
    
    func download(at row: Int) {
        
        currentExt = viewModel.streams[row].extension
        
        if let url = URL(string: viewModel.streams[row].url), let destenation = destinationURL(file: url) {
            
            interactor.download(DownloadItem(url, dest: destenation))
        }
    }
    
    func destinationURL(file url: URL) -> URL? {
        
        guard let documentsDirectoryURL = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
            return nil
        }
        
        let destinationURL = documentsDirectoryURL.appendingPathComponent(UUID().uuidString).appendingPathExtension(currentExt)
        
        return destinationURL
    }
    
    func process(local url: URL?) {
        
        guard let url = url else {
            return
        }
        
        DispatchQueue.main.async { [weak self] in
            let activityViewController = UIActivityViewController(activityItems: [url, "Check this out!"], applicationActivities: nil)
            self?.wireframe.viewController.present(activityViewController, animated: true)
        }
    }
}
