//
//  DetailInteractor.swift
//  youtube-loader-ios
//
//  Created by Dima Virych on 26.01.2020.
//  Copyright (c) 2020 Virych. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Networking

final class DetailInteractor {
    
    let service: NetworkingService
    
    var output: ((URL?) -> Void)!
    
    init(service: NetworkingService) {
        
        self.service = service
    }
}

// MARK: - Extensions -

extension DetailInteractor: DetailInteractorInterface {
    
    func download(_ url: URL) {
        
        service.download(url: url, destURL: <#URL?#>, completion: output)
    }
}
