//
//  DetailWireframe.swift
//  youtube-loader-ios
//
//  Created by Dima Virych on 26.01.2020.
//  Copyright (c) 2020 Virych. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import BaseViper
import Networking

final class DetailWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Detail", bundle: nil)

    // MARK: - Module setup -

    init(viewModel: VideoViewModel) {
        let moduleViewController = storyboard.instantiateViewController(ofType: DetailViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = DetailInteractor(service: NetworkService())
        let presenter = DetailPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        presenter.viewModel = viewModel
        moduleViewController.presenter = presenter
    }
}

// MARK: - Extensions -

extension DetailWireframe: DetailWireframeInterface {
}
